'use strict';

/**
 * Exports skills to Markdown or JSON for projects that don't use MCP.
 * Usage: skill-brain export [--output=SKILLS.md] [--format=md|json] [--project=name] [--domain=...]
 */

const fs = require('fs');
const path = require('path');

function groupBy(arr, key) {
  return arr.reduce((acc, item) => {
    const k = item[key] || 'General';
    (acc[k] = acc[k] || []).push(item);
    return acc;
  }, {});
}

function sanitize(str) {
  return (str || '').replace(/\n{3,}/g, '\n\n').trim();
}

/**
 * Render a single skill as Markdown.
 * @param {object} skill
 * @returns {string}
 */
function skillToMarkdown(skill) {
  const lines = [];
  lines.push(`### ${skill.name}`);
  lines.push('');
  if (skill.description) lines.push(`> ${skill.description}`);
  lines.push('');

  const meta = [];
  if (skill.id) meta.push(`**ID:** \`${skill.id}\``);
  if (skill.severity) meta.push(`**Severity:** ${skill.severity}`);
  if (skill.domain) meta.push(`**Domain:** ${skill.domain}`);
  if (skill.tags && skill.tags.length) meta.push(`**Tags:** ${skill.tags.join(', ')}`);
  if (meta.length) { lines.push(meta.join(' · ')); lines.push(''); }

  if (skill.template) {
    lines.push(sanitize(skill.template));
    lines.push('');
  }

  lines.push('---');
  return lines.join('\n');
}

/**
 * Render all skills to a Markdown document.
 * @param {object[]} skills
 * @param {{ projectName?: string, domain?: string }} options
 * @returns {string}
 */
function toMarkdown(skills, options = {}) {
  const { projectName, domain } = options;
  const filtered = domain ? skills.filter(s => (s.domain || '').toLowerCase().includes(domain.toLowerCase())) : skills;

  const lines = [];
  lines.push('# Skills Reference');
  lines.push('');
  if (projectName) lines.push(`> Project: **${projectName}**`);
  lines.push(`> Generated by [skill-brain](https://github.com/snpanigrahi88/skill-brain) on ${new Date().toISOString().split('T')[0]}`);
  lines.push(`> Total skills: **${filtered.length}**`);
  lines.push('');

  if (!filtered.length) {
    lines.push('_No skills found._');
    return lines.join('\n');
  }

  const grouped = groupBy(filtered, 'domain');
  const domains = Object.keys(grouped).sort();

  lines.push('## Table of Contents');
  lines.push('');
  domains.forEach(d => {
    const anchor = d.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    lines.push(`- [${d}](#${anchor}) (${grouped[d].length})`);
  });
  lines.push('');

  for (const d of domains) {
    lines.push(`## ${d}`);
    lines.push('');
    for (const skill of grouped[d]) {
      lines.push(skillToMarkdown(skill));
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Export skills to disk.
 * @param {object[]} skills
 * @param {{ outputPath: string, format?: 'md'|'json', projectName?: string, domain?: string }} options
 */
function exportToFile(skills, options = {}) {
  const { outputPath, format = 'md', projectName, domain } = options;

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  let content;
  if (format === 'json') {
    const filtered = domain ? skills.filter(s => (s.domain || '').toLowerCase().includes(domain.toLowerCase())) : skills;
    content = JSON.stringify({ generated: new Date().toISOString(), total: filtered.length, skills: filtered }, null, 2);
  } else {
    content = toMarkdown(skills, { projectName, domain });
  }

  fs.writeFileSync(outputPath, content, 'utf8');
  return { outputPath, total: skills.length, format };
}

module.exports = { toMarkdown, exportToFile, skillToMarkdown };
